### ISSUE TITLE
API appears async, but it's not

### ISSUE THREAD

**Issue by digitalnature** [google/closure-compiler-npm#107]
What's the point of passing a callback, if the compiler is synchronous?

And the `path` argument doesn't seem to change anything. Then the returned `path` property always points to compiled.js, which doesn't exist.

The API is very poorly designed. Why was the -js repository deprecated, if the new one is not finished?

**Comment by leeoniya** [comment]
https://github.com/google/closure-compiler-npm/issues/106#issuecomment-414648295

**Comment by ChadKillingsworth** [comment]
The JS repo was deprecated because we wanted developers to seamlessly move between platforms. Also, the various build tools were supported at different levels.

This repo has been around a while - and the API was originally designed to use the command line version first. As linked, we're moving towards a seemless api, but that change takes time.
