### ISSUE TITLE
Not latest version of closure compiler on npmjs.org

### ISSUE THREAD

**Issue by banguit** [google/closure-compiler-npm#309]
I just noticed that the current version is [v20240609](https://github.com/google/closure-compiler/releases/tag/v20240609) but in npm repository I see [v20240317.0.0](https://www.npmjs.com/package/google-closure-compiler).

Is deployment to npm is still supported?

Thanks,
Dima

**Comment by ChadKillingsworth** [comment]
We're experimenting with new deployment methods which is why you see the newer tag, but the newest deployed version is 20240317.0.0. You'll also see that's the newest version deployed to Maven: https://mvnrepository.com/artifact/com.google.javascript/closure-compiler

npm is definitely still supported and will continue to be.
