### ISSUE TITLE
--js equals --js_output_file no error message in stdout/stderr

### ISSUE THREAD

**Issue by cancerberoSgx** [google/closure-compiler-npm#88]
When you run the command with --js and --js_output_file pointing to the same file there is an error and that's fine if the tool doesn't support it but No message is printed in stdout/stderr. I assume there was an error because the process exit code is different than zero and there was no transformation in given file

In other words, executing : 

```
npx google-closure-compiler --js=static/typescript.js --js_output_file=static/typescript.min.js
```

Expected behavior: Message saying that there was an error.

Actual behavior: No message saying that something went wrong.

**Comment by ChadKillingsworth** [comment]
The compiler specifically checks for that case to prevent you from destroying source files. However the lack of an error message is a problem. I'll see if I can figure out why that is.

This happens when running the jar as well. I've moved the issue to the main repo: https://github.com/google/closure-compiler/issues/2990
